apiVersion: v1
kind: Service
metadata:
  name: learnflow-backend
  namespace: learnflow
  labels:
    app: learnflow-backend
spec:
  selector:
    app: learnflow-backend
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
