apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: learnflow-ingress
  namespace: learnflow
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: learnflow.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: learnflow-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: learnflow-frontend
                port:
                  number: 3000
